Repository SHPE-at-UCI/shpe-uci-portal, pull requests merged in 2020-10, with the labels that each got.

#98 Resume upload api 1.1
  .gitignore
  app/__init__.py
  app/routes/auth.py
  app/routes/dashboard.py
  app/templates/dashboard.html
  app/utils/client_id.json
  app/utils/google_drive_api.py
Labels: back-end

#102 Added new modules in requirements.txt
  requirements.txt
Labels: dependencies

#113 Added is_admin field to sign up form
  app/routes/auth.py
Labels: dashboard
